# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[[ "$-" =~ 'i' ]] || return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTFILESIZE=100000
HISTCONTROL=ignoreboth
PROMPT_COMMAND='history -a'
PROMPT_DIRTRIM=1

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
stty -ixon

function nonzero_return() {
	RETVAL=$?
	[ $RETVAL -ne 0 ] && echo "$RETVAL"
}
export PS1="\[\e[30;41m\]\`nonzero_return\`\[\e[m\]\[\e[32m\]\u\[\e[m\]@\[\e[37m\]\h\[\e[m\]:\W# "

bind 'set show-all-if-ambiguous on'
bind 'set completion-ignore-case on'

[[ -f ~/.bashrc_aliases ]] && . .bashrc_aliases
[[ -f ~/.bashrc_functions ]] && . .bashrc_functions
[[ -f ~/.bashrc_ssh ]] && . .bashrc_ssh
[[ -f ~/.bashrc_env ]] && . .bashrc_env

[[ -f /etc/bash_completion ]] && . /etc/bash_completion

[[ -f ~/.bashrc_local ]] && . .bashrc_local
true
